<?php

namespace AppBundle\Repository;

/**
 * SRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SRepository extends \Doctrine\ORM\EntityRepository
{
}
